#!/bin/bash -e

cd $(git rev-parse --show-toplevel)
mkdir -p dist

BASE_VERS=base
NEW_VERS=0.0.1
FILE_NAME=pg_defaults

# generate data for available versions
./util/versions | ./util/mk_copy_table pg_defaults_versions > $FILE_NAME--$BASE_VERS--$NEW_VERS.sql

# build everything so we have the source config files
./util/update_all_versions

# generate the compressed output for the table data
./util/compress_version_data | ./util/mk_copy_table pg_defaults_gucs >> $FILE_NAME--$BASE_VERS--$NEW_VERS.sql

