#!/bin/bash

mkdir -p logs

bindir=$(cd $(dirname $0); pwd)

for version in $($bindir/versions); do
    echo "Building version $version"
    $bindir/get_revision_defaults $version >logs/$version.log 2>&1
done
